name: Configure GitHub Gist

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main
    paths:
      - 'static/github-gist-config.js'

jobs:
  configure-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure GitHub Gist
        run: |
          # 创建配置文件
          cat > static/github-gist-config.js << 'EOF'
          // GitHub Gist 配置文件
          // 此文件由GitHub Actions自动生成，包含敏感信息
          
          window.GITHUB_GIST_TOKEN = "${{ secrets.BLOG_GIST_TOKEN }}"
          window.GITHUB_GIST_ID = "${{ secrets.BLOG_GIST_ID }}"
          EOF
          
          echo "GitHub Gist配置文件已生成"
          
          # 显示配置文件内容（不显示敏感信息）
          echo "配置文件内容（敏感信息已隐藏）："
          cat static/github-gist-config.js | sed 's/window\.GITHUB_GIST_TOKEN = .*/window.GITHUB_GIST_TOKEN = "[REDACTED]"/' | sed 's/window\.GITHUB_GIST_ID = .*/window.GITHUB_GIST_ID = "[REDACTED]"/'

      - name: Commit and push configuration
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add static/github-gist-config.js
          git diff --staged --quiet || git commit -m "Update GitHub Gist configuration"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}